The run id is coouhy3a
Epoch: 1 / 30:   0%|                                                                                                                                        | 0/1080 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 504, in <module>
    main(args)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 445, in main
    train(args, model, train_loader, test_loader, device, restart = args.restart)
  File "/home/temp/Sami_DLV3+_Brickfield/mainDLV3+.py", line 272, in train
    loss.backward()
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/home/temp/miniconda3/envs/lightning/lib/python3.12/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 416.00 MiB. GPU 0 has a total capacity of 47.71 GiB of which 297.62 MiB is free. Process 2858169 has 16.29 GiB memory in use. Including non-PyTorch memory, this process has 25.32 GiB memory in use. Of the allocated memory 24.08 GiB is allocated by PyTorch, and 654.99 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
